[client]
showSidebarNavigation = false

[theme]
#highlight color = #41af9e teal green
#primary text = #d2defe off white purple ish
#secondary text = #868fae grey
#tertiary text = #5d6685 dark grey
#background = #0a192f

#base = "dark"
primaryColor = "#d2defe"
backgroundColor = "#071324"
secondaryBackgroundColor = "#0a192f"
textColor = "#d9e3ff"
linkColor = "#41af9e"
codeBackgroundColor = "#8458B3"
baseRadius = "medium"
buttonRadius = "medium"
borderColor = "#5d6685"
#dataframeBorderColor = "#FFFFFF"
showWidgetBorder = true
baseFontSize = 16
showSidebarBorder = true