[client]
showSidebarNavigation = false

[theme]
#highlight color = #41af9e teal green
#primary text = #d2defe off white purple ish
#secondary text = #868fae grey
#tertiary text = #5d6685 dark grey
#background = #0a192f

#base = "dark"
primaryColor = "#4cd4bf"
backgroundColor = "#071324"
secondaryBackgroundColor = "#0a192f"
textColor = "#d9e3ff"
linkColor = "#4cd4bf"
codeBackgroundColor = "#0a192f"
baseRadius = "medium"
buttonRadius = "medium"
borderColor = "#4cd4bf"
font = "sans-serif"
codeFont = "monospace"
#dataframeBorderColor = "#FFFFFF"
showWidgetBorder = true
baseFontSize = 15
showSidebarBorder = true